# Generated by Django 3.0.5 on 2020-04-26 04:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(default=None, help_text='Contact number', max_length=31),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=240),
        ),
    ]
