# Generated by Django 3.0.5 on 2020-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
