# Generated by Django 3.0.5 on 2020-04-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0005_auto_20200423_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='ordered_items',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.CreateModel(
            name='UserOrderQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.FinalOrder')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
