# Generated by Django 3.0.5 on 2020-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200423_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ATC_status',
        ),
        migrations.RemoveField(
            model_name='finalorder',
            name='ordered_items',
        ),
        migrations.AlterField(
            model_name='userorderquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
