# Generated by Django 3.0.5 on 2020-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200424_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
