# Generated by Django 3.0.5 on 2020-04-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor'),
        ('orders', '0009_auto_20200424_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductColor'),
        ),
        migrations.AddField(
            model_name='userorderquantity',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductColor'),
        ),
    ]
