# Generated by Django 3.0.5 on 2020-04-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200425_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='userorderquantity',
            name='quantity',
        ),
    ]
